# Generated by Django 3.0.5 on 2020-04-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nom')),
                ('picture', models.URLField(verbose_name='image')),
                ('content', models.TextField(verbose_name='contenue')),
                ('realease_date', models.DateField(verbose_name='Date de livraison')),
                ('url', models.URLField(verbose_name='Url')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nom')),
                ('project', models.ManyToManyField(related_name='project', to='projects.Project')),
            ],
        ),
    ]
