# Generated by Django 3.0.5 on 2020-04-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book name')),
                ('author', models.CharField(max_length=100, verbose_name='auteur')),
                ('content', models.TextField(blank=True, max_length=500, null=True, verbose_name='contenu')),
                ('embed_code', models.TextField(max_length=1000, verbose_name='source')),
                ('post_date', models.DateTimeField(auto_now=True, verbose_name='Date du post')),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.CharField(max_length=100, verbose_name='auteur'),
        ),
    ]
