# Generated by Django 3.0.5 on 2020-04-12 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200412_0042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
