# Generated by Django 3.0.5 on 2020-04-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200412_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='embed_code',
            field=models.TextField(max_length=1000, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='project_type',
            field=models.CharField(choices=[('web_app', 'Web Appsss'), ('web_site', 'Web site'), ('ios_app', 'Ios App'), ('desktop_app', 'Desktop App')], max_length=20, verbose_name='Type de projet'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='embed_code',
            field=models.TextField(max_length=500, verbose_name='code'),
        ),
    ]
