# Generated by Django 3.0.5 on 2020-04-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200418_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='project_type',
            field=models.CharField(choices=[('web app', 'Web App'), ('web site', 'Web site'), ('Ios app', 'Ios App')], max_length=20, verbose_name='Type de projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(upload_to=None, verbose_name='Image'),
        ),
    ]
