# Generated by Django 3.0.5 on 2020-04-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200420_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(upload_to='projects/', verbose_name='Image'),
        ),
    ]
